### PR TITLE
docker container for backend

### PR DESCRIPTION
**Pull request by dmilet**
@jkbits1 I changed the Dockerfile for nodeApp

The way I run this is , from the top directory of the repo
--- create images
sudo docker-compose -f docker-compose-build.yml build
--- start containers
sudo docker-compose -f docker-compose.yml up

cp_api is available on local port 3030, and connects to cp_pg_server via docker

curl http://127.0.0.1:3030/unmatched-drivers

todo  : 
- add nginx as container, and link to cp_api
- add matching engine as container, link to cp_pg_server
- add email sender, link to cp_pg_server
- add sms sender, link to cp_pg_server
- update Vagrantfile to build and deploy containers

### CODE REVIEW

**Comment by jkbits1** [comment]
@dmilet thanks for this PR

Firstly, great to have someone involved who's able to contribute to the docker setup 👍 

I've only had the opportunity to take a brief look at these changes, so, at a higher level, what are your goals for this PR?

To add some context to the existing docker setup, it exists for the purposes described in:
https://github.com/voteamerica/backend/tree/master/docker. Any changes will need to fit in with these purposes.

1) Support for various development environments and automated testing. Also, manual tests of PRs.

2) Travis CI is the second use, with automatic build checks confirming the code provides a working system for a year now: https://travis-ci.org/voteamerica/backend/builds
(two weeks ago, the checks started to fail, it may be a recent PR or a dependency issue. It's a bit elusive but important to fix, so one of my priorities)

As you can see from the docker folder, a variety of setups are supported and new setups and are fine.

**Comment by dmilet** [comment]
@jkbits1 purpose of this PR is to have a simpler docker setup of the back end to deploy on new VM. No exposed psql port, different services running in different containers ( nginx, db, api, matching engine, email handler, sms handler) 
I couldn’t succeed in using what’s there I may be missing bits and pieces. I wonder if some files have too many paths hardcoded from your own environment 
The current docker setup works great with Travis apparently so I’m not changing that. But I also don’t see how to use that to deploy on a new vm on DO


Btw, I think the reason the Travis build fails now is because the test data (available dates) are now in the past. See Travis log on the first error if it makes sense to you. Where are those tests stored?

**Comment by dmilet** [comment]
@jkbits1 This PR is now complete with docker containers for the backend and a Vagrant configuration  for VirtualBox and DigitalOcean
I'll deploy the same to existing DO VM soon

**Comment by jkbits1** [comment]
@dmilet great, I'll take a look at this tomorrow

**Comment by dmilet** [comment]
see updated operations documentation in 
https://docs.google.com/document/d/13BHwoK_duSw7BM_ny1KWxP2W4aaJ-QTb96W-hih1cPE/edit

**Comment by jkbits1** [comment]
@dmilet only had a chance to scan these changes so far, but all looks good. There's at least one file that shouldn't be deleted and I need to do some actual checks, so will do that review tomorrow

**Comment by dmilet** [comment]
Apologies, Jon, didn't realize you were using those files. I added them back.
About the location of the docker executable. on Linux, docker is in /usr/bin. What does the command "uname -io" return for you? I could enhance common-sudo-fix.sh to set the path to docker depending on the output from uname command.

**Comment by jkbits1** [comment]
@dmilet thanks for restoring the files 👍 

Nice idea to adapt your new .sh file. 

Here's a short session on a docker machine environment that's just been started, and the call to `uname -io` is at the end. A brief google based on the info in the next paragraph showed up `uname -r` for a completely unrelated subject but the result looks distinctive.

If the info at the end of this web page is current (which is hard to be absolutely certain about):
https://github.com/boot2docker/boot2docker
then docker toolbox uses a version of `Tiny Core Linux`. 

```
$ docker-machine ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 18.02.0-ce, build HEAD : 99245f4 - Thu Feb  8 17:43:39 UTC 2018
Docker version 18.02.0-ce, build fc4de44
docker@default:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
docker@default:~$ ls /usr/local/bin/docker
/usr/local/bin/docker
docker@default:~$ uname -io
unknown GNU/Linux
docker@default:~$ uname -r
4.4.115-boot2docker
docker@default:~$
```

**Comment by dmilet** [comment]
see changed docker/common-sudo-fix.sh
It should now detect  a docker executable in /usr/local/bin and use that one. if not found it will use the one in /usr/bin

**Comment by jkbits1** [comment]
@dmilet great 👍 this change makes everything work fine on Docker Toolbox

**Pull request merged**
