### PR TITLE
First PR on 2017 backend!

### PR DESCRIPTION
**Pull request by dmilet**
Hello,
This is kind of a massive PR.
See the README in the db directory

Note that there is an impact on the front end web app.
The front end web app should no longer directly insert into the driver/rider/helper tables, there are now dedicated functions for that.

I started writing unit tests using pytest too, they're in the "test" subdirectory.

### CODE REVIEW

**Comment by jkbits1** [comment]
@dmilet great, I'll test this. Excellent to have some tests

**Comment by jkbits1** [comment]
@dmilet I created the db fine from the scripts, but the node app had errors when I tested it. Was this the same for you?

**Comment by dmilet** [comment]
Jon, I have not reinstalled the node app yet, and I have not tried it.
I would expect that a few changes are needed on the node app. 
The nov2016 and stage schemas are replaced by a single carpoolvote schema. 
Make sure the DB user you connect with is in the carpool_web_role.
Where do you run the node app? Do I have access to the logs?

**Comment by dmilet** [comment]
I've just added one commit, for a missing select permission on zip_codes tables, just in case it's related to the issues you mentioned

**Comment by dmilet** [comment]
@jkbits1 Jon, any objections against merging now?
This code is is good shape, I'm going to start setting up nginx and the node app.

**Pull request merged**
