### PR TITLE
Change 'noreply' to 'Carpool Vote' in emails

### PR DESCRIPTION
**Pull request by sdotson**
For issue #156 .

### CODE REVIEW

**Comment by jkbits1** [comment]
@sdotson thanks for this, looks good to me 👍 

@dmilet any thoughts on this?

**Comment by dmilet** [comment]
Hello, 
Change looks OK to me.
Should I merge and deploy it?

**Comment by jkbits1** [comment]
@dmilet hi there, I agree with you, go ahead and deploy

**Comment by jkbits1** [comment]
@sdotson thanks again. Merged now

**Pull request merged**
