### PR TITLE
first implementation of cancel_ride_request

### PR DESCRIPTION
**Pull request by dmilet**
No need to merge now, this is just FYI
I implemented the first function to support USER STORY 003.

4 functions to go... will be faster for the next ones.

### CODE REVIEW

**Comment by jkbits1** [comment]
great, will test this out :+1:

**Comment by jkbits1** [comment]
All looks good enough to use given the following tests - matching engine works. cancel_ride_request correctly rejected invalid phone number, cancelled a match when given correct phone number.

Just as feedback, after cancel ride, driver state remains at Match Proposed.

**Comment by dmilet** [comment]
@jkbits1 Thanks for the feedback. I'll review the code.

**Comment by dmilet** [comment]
Functions are implemented.  Partially tested, help is appreciated.
-- actions by rider
--nov2016.rider_cancel_ride_request(UUID, phone number or lastname ?)
--nov2016.rider_cancel_confirmed_match(UUID_driver, UUID_rider, score, rider’s phone number or rider’s lastname ?)

-- actions by driver
--nov2016.driver_cancel_drive_offer(UUID, phone number or lastname ?)
--nov2016.driver_cancel_confirmed_match(UUID_driver, UUID_rider, driverr’s phone number or driver’s lastname ?)
--nov2016.driver_confirm_match(UUID_driver, UUID_rider, score, driver’s phone number or driver’s lastname ?)

-- functions return character varying with explanatory text of error condition. Empty string if success

Also, added fields for preferred contact method for driver and rider. See in backend/api_def.txt

I would like to remove RiderVotingState (unused) , please let me know when the node app no longer uses it.

**Comment by jkbits1** [comment]
@dmilet great, this is my area to focus on for the next few hours

**Comment by jkbits1** [comment]
@dmilet this is excellent, thanks you :+1: 

the node app in this PR uses the new status fns
https://github.com/voteamerica/backend/pull/50/files

Regarding RiderVotingState I believe it is now necessary to freeze the db schema except for essential changes. Each change has the potential to break POSTs and makes debugging a slower process

**Pull request merged**
